### PR TITLE
fix: Resources and other types (Conditions, Outputs, etc) cannot have the same name

### LINKED ISSUE #365: Conditions and Resources can have the same name in CFN, but not in CDK
When a Condition and Resource have the same name this fails in CDK:
`There is already a Construct with name 'AlwaysTrue' in [Test]`

We need to scope the names for conditions and change back the logical IDs.

See: https://github.com/cdklabs/decdk/blob/1bb1ad29136d620b67a975edbc339a46873c0ea5/test/evaluate/fixtures.test.ts#L19

### PR DESCRIPTION
**Pull request by mrgrain**
Fixes #365

### CODE REVIEW

File: src/evaluate/evaluate.ts [hunk 1]
```diff
@@ -45,28 +45,31 @@ export class Evaluator {
...
+    const scope = new Construct(this.context.stack, '$Mappings');
+    this.context.template.mappings.forEach((mapping, mapName) =>
+      new cdk.CfnMapping(scope, mapName, {
+        mapping: mapping.toObject(),
+      }).overrideLogicalId(mapName)
     );
   }
 
   private evaluateParameters() {
+    const scope = new Construct(this.context.stack, '$Parameters');
```
Comment (otaviomacedo) [inline src/evaluate/evaluate.ts:68]: Ha! Nice trick.

Comment (mrgrain) [reply src/evaluate/evaluate.ts:68]: Thanks, but it's stolen from here: https://github.com/aws/aws-cdk/blob/af1fb7ce4468b14aecbf24e2cc1c6efeb29761b7/packages/@aws-cdk/cloudformation-include/lib/cfn-include.ts#L136

**Review by otaviomacedo — APPROVED** [review]
